### ISSUE TITLE
Server Start issue

### ISSUE THREAD

**Issue by ggr93** [eclair4151/AlexaControlledSamsungTV#6] opened 2018-05-10 11:27 UTC
I appear to be having some issues attempting to start the server....

Any thoughts?

starting server...
Traceback (most recent call last):
  File "alexasmartcli.py", line 181, in <module>
    mqtt_server.startServer(options.mute)
  File "/opt/AlexaControlledSamsungTV/helpers/mqtt_server.py", line 235, in startServer
    myMQTTClient.connect()
  File "/home/USERNAME/.local/lib/python3.5/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 408, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/home/USERNAME/.local/lib/python3.5/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 168, in connect
    self.connect_async(keep_alive_sec, self._create_blocking_ack_callback(event))
  File "/home/USERNAME/.local/lib/python3.5/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 179, in connect_async
    rc = self._internal_async_client.connect(keep_alive_sec, ack_callback)
  File "/home/USERNAME/.local/lib/python3.5/site-packages/AWSIoTPythonSDK/core/protocol/internal/clients.py", line 113, in connect
    rc = self._paho_client.connect(host, port, keep_alive_sec)
  File "/home/USERNAME/.local/lib/python3.5/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 654, in connect
    return self.reconnect()
  File "/home/USERNAME/.local/lib/python3.5/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 776, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/lib/python3.5/socket.py", line 693, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

**Comment by eclair4151** [comment] 2018-05-12 21:19
Hmm I may need some more info as I am unable to reproduce unless i disconnect my pi from the network. Another person also had the same issue too. Can you confirm that the pi is connected to the internet while you are staring it?

**Comment by ggr93** [comment] 2018-05-12 22:01
I’m running this on my Ubuntu 16.04 LTS headless server but I can confirm I am connected to the internet

Does this specifically need to run on Pi? If so any distro specifically?

**Comment by eclair4151** [comment] 2018-05-12 22:09
oh no it can run on anything that can run python. the pi is just what most people use. 

it seems to be a networking issue with the AWS library. 

see
https://github.com/aws/aws-iot-device-sdk-python/issues/101

i would try first updating the package because the one in my requirements is 2 behind

so try
pip install AWSIoTPythonSDK --upgrade

and see the comment in the github issue

**Comment by ggr93** [comment] 2018-05-12 22:56
Okay will try tomorrow morning (UK) and let you know how it goes

Thank you!

**Comment by eclair4151** [comment] 2018-05-15 11:23
were you able to try this?

**Comment by ggr93** [comment] 2018-05-22 07:00
Sorry about delayed reply, I was traveling 
Attempted the fix with no luck

Also tried fresh install via newly installed Ubuntu 16.04 desktop with no luck. Even tried placing temp any any any rule on my firewall too to ensure traffic could get out but no luck with that either

**Comment by eclair4151** [comment] 2018-05-22 12:32
can you try changing the DNS of your server to something like 8.8.8.8 and 8.8.4.4 
the error sounds like it is unable to find the correct ip. 

can you also go on that server and ping afkx1f9takwol.iot.us-east-1.amazonaws.com and make sure you are getting a response

**Comment by eclair4151** [comment] 2018-06-05 14:40
I have gotten confirmation that changing the DNS on your pi fixes this issue. Closing for now. If this issue comes up again and this doesn't fix it i will re open

**Closed as completed by eclair4151** 2018-06-05 14:40 UTC
Labels: bug
