### ISSUE TITLE
Channels with 0

### ISSUE THREAD

**Issue by g10chy** [eclair4151/AlexaControlledSamsungTV#16] opened 2018-12-20 17:45 UTC
When I try and change the channel to 103. I can see the request correctly but on the TV it changes to channel 13:

`Received a new message:
b'{"channel_data": {"channel": {"number": "103"}, "channelMetadata": {}}, "operation": "ChangeChannel", "endpointid": "40:16:3b:42:e1:7f"}'
from topic:
channel/28ee4056-8450-43a0-94da-d26404322688`

I have to say change channel to 1003 to get it to then change correctly to 103 on the TV:

`Received a new message:
b'{"channel_data": {"channel": {"number": "1003"}, "channelMetadata": {}}, "operation": "ChangeChannel", "endpointid": "40:16:3b:42:e1:7f"}'
from topic:
channel/28ee4056-8450-43a0-94da-d26404322688`

**Comment by eclair4151** [comment] 2018-12-20 18:06
try this go into
AlexaControlledSamsungTV/helpers/mqtt_server.py

and change line 104 that says

time.sleep(0.05)

to

time.sleep(0.75)

**Comment by g10chy** [comment] 2018-12-20 18:31
That’s done the trick thanks. 

TurnOff seems to have stopped working though?

**Comment by eclair4151** [comment] 2018-12-20 18:57
Does the command give an error or just not turn off the tv? if its the later try giving it some time. sometimes i have noticed if i am rapidly turning the tv off an on the power off command stops working for a bit. (give it like 10 minutes and see if anything happens). If it was working before though then i'm not quite sure what could be wrong besides that

**Comment by eclair4151** [comment] 2019-01-09 13:24
just wanted to follow up. If the issue is resolved let me know so i can close the issue

**Closed as completed** 2019-01-18 14:53 UTC
